In [1]:
# Add the Pandas dependency.
import pandas as pd
import numpy as np

In [2]:
url_Climate_data_complete = 'https://raw.githubusercontent.com/Ricardolpz99/Turn-Green/main/Database/Clean/Climate_data_complete_(no_null_values).csv'
Climate_data_complete_df = pd.read_csv(url_Climate_data_complete)

In [3]:
Climate_data_complete_df.head()

,Unnamed: 0,Entity,Code,Year,Annual CO2 emissions (per capita),Renewables (% sub energy)
0,0,Africa,AFR,1965,0.6750,5.526
1,1,Africa,AFR,1966,0.6814,5.862
2,2,Africa,AFR,1967,0.7124,6.069
3,3,Africa,AFR,1968,0.7541,6.730
4,4,Africa,AFR,1969,0.7938,7.669

In [4]:
Climate_data_complete_df.drop(['Unnamed: 0'], axis=1)

,Entity,Code,Year,Annual CO2 emissions (per capita),Renewables (% sub energy)
0,Africa,AFR,1965,0.6750,5.526
1,Africa,AFR,1966,0.6814,5.862
2,Africa,AFR,1967,0.7124,6.069
3,Africa,AFR,1968,0.7541,6.730
4,Africa,AFR,1969,0.7938,7.669
...,...,...,...,...,...
3985,World,OWID_WRL,2016,4.7496,10.239
3986,World,OWID_WRL,2017,4.7595,10.618
3987,World,OWID_WRL,2018,4.8022,10.978
3988,World,OWID_WRL,2019,4.7582,11.437
3989,World,OWID_WRL,2020,4.4654,12.553

In [5]:
url_Climate_data_complete_generated = 'https://raw.githubusercontent.com/Ricardolpz99/Turn-Green/main/Database/Clean/Climate_data_complete_generated.csv'
Climate_data_complete_generated_df=pd.read_csv(url_Climate_data_complete_generated)

In [6]:
Climate_data_complete_generated_df.drop(['Unnamed: 0'], axis=1)

,Entity,Code,Year,Annual CO2 emissions (per capita),Solar Generation - TWh,Wind Generation - TWh,Hydro Generation - TWh,Geo Biomass Other - TWh
0,Africa,AFR,2000,1.0936,0.011941,0.175500,75.245817,2.269063
1,Africa,AFR,2001,1.0645,0.014960,0.415580,80.864115,2.335353
2,Africa,AFR,2002,1.0489,0.017871,0.443584,85.181468,2.286400
3,Africa,AFR,2003,1.1094,0.021329,0.535599,82.872601,2.622400
4,Africa,AFR,2004,1.1603,0.025761,0.768281,87.405469,2.978850
...,...,...,...,...,...,...,...,...
1200,World,OWID_WRL,2016,4.7496,328.385208,962.227395,4018.671591,560.681082
1201,World,OWID_WRL,2017,4.7595,446.054164,1140.310949,4066.718275,593.790980
1202,World,OWID_WRL,2018,4.8022,576.951248,1269.520536,4176.687496,632.173911
1203,World,OWID_WRL,2019,4.7582,707.918495,1418.170046,4227.883280,663.134292
1204,World,OWID_WRL,2020,4.4654,855.724690,1591.213512,4296.802045,700.068651

In [7]:
Climate_data_complete_generated_df.head(60)

,Unnamed: 0,Entity,Code,Year,Annual CO2 emissions (per capita),Solar Generation - TWh,Wind Generation - TWh,Hydro Generation - TWh,Geo Biomass Other - TWh
0,35,Africa,AFR,2000,1.0936,0.011941,0.175500,75.245817,2.269063
1,36,Africa,AFR,2001,1.0645,0.014960,0.415580,80.864115,2.335353
2,37,Africa,AFR,2002,1.0489,0.017871,0.443584,85.181468,2.286400
3,38,Africa,AFR,2003,1.1094,0.021329,0.535599,82.872601,2.622400
4,39,Africa,AFR,2004,1.1603,0.025761,0.768281,87.405469,2.978850
5,40,Africa,AFR,2005,1.1547,0.030676,0.780382,89.065734,3.009669
6,41,Africa,AFR,2006,1.1613,0.038957,0.852566,92.244353,3.770405
7,42,Africa,AFR,2007,1.1763,0.051533,1.016223,95.340562,3.142048
8,43,Africa,AFR,2008,1.1968,0.073232,1.311778,97.157209,3.267396
9,44,Africa,AFR,2009,1.1762,0.096153,1.589231,99.761137,3.562722
10,45,Africa,AFR,2010,1.1725,0.212521,2.284582,107.426833,3.825407
11,46,Africa,AFR,2011,1.1809,0.601454,2.386504,110.444821,3.929657
12,47,Africa,AFR,2012,1.1456,0.994443,2.515630,110.952300,4.085025
13,48,Africa,AFR,2013,1.1227,0.788910,3.593447,117.638846,4.430894
14,49,Africa,AFR,2014,1.1837,1.937700,5.060073,123.726795,5.521056
15,50,Africa,AFR,2015,1.1191,3.592173,8.910686,120.167836,7.191202
16,51,Africa,AFR,2016,1.1189,5.120197,11.176371,116.718805,7.281251
17,52,Africa,AFR,2017,1.1131,6.902447,12.457774,125.816522,7.653766
18,53,Africa,AFR,2018,1.0865,8.295434,14.770723,133.140498,8.097891
19,54,Africa,AFR,2019,1.0772,10.906902,18.857729,137.215511,8.228082
20,55,Africa,AFR,2020,0.9896,12.407782,21.789843,142.574996,8.068135
21,145,Argentina,ARG,1998,3.8668,0.000017,0.032541,32.421788,0.463881
22,146,Argentina,ARG,1999,4.0388,0.000026,0.034781,26.530071,0.650455
23,147,Argentina,ARG,2000,3.8610,0.000036,0.034758,34.034010,0.675014
24,148,Argentina,ARG,2001,3.5949,0.000043,0.049361,41.903263,0.609326
25,149,Argentina,ARG,2002,3.3011,0.000047,0.073405,41.467051,0.850249
26,150,Argentina,ARG,2003,3.5347,0.000065,0.077954,39.080081,1.014080
27,151,Argentina,ARG,2004,4.0799,0.000070,0.072446,35.402879,0.900295
28,152,Argentina,ARG,2005,4.1507,0.000081,0.071720,39.350091,1.074073
29,153,Argentina,ARG,2006,4.4441,0.000090,0.069640,43.624000,1.567410
30,154,Argentina,ARG,2007,4.3908,0.000109,0.061593,37.741000,1.575709
31,155,Argentina,ARG,2008,4.6932,0.000144,0.041951,37.199000,1.693536
32,156,Argentina,ARG,2009,4.4204,0.000076,0.036832,40.783000,1.728756
33,157,Argentina,ARG,2010,4.5661,0.000086,0.025352,40.543000,2.013255
34,158,Argentina,ARG,2011,4.6048,0.001614,0.026591,39.641000,2.190206
35,159,Argentina,ARG,2012,4.5914,0.008173,0.369862,36.876000,2.453822
36,160,Argentina,ARG,2013,4.5060,0.015074,0.453355,40.700000,2.457350
37,161,Argentina,ARG,2014,4.4247,0.015944,0.619491,40.864000,2.302025
38,162,Argentina,ARG,2015,4.4667,0.014683,0.593335,41.770900,2.378259
39,163,Argentina,ARG,2016,4.3894,0.014273,0.547359,38.254393,1.963409
40,164,Argentina,ARG,2017,4.2744,0.016417,0.611567,41.542979,2.383655
41,165,Argentina,ARG,2018,4.0824,0.108130,1.412743,41.647865,0.473010
42,166,Argentina,ARG,2019,3.7419,0.799698,4.995966,37.066787,0.622945
43,167,Argentina,ARG,2020,3.4733,1.344341,9.470298,30.543592,0.413941
44,196,Australia,AUS,1993,16.5495,0.014600,0.002000,16.387000,0.670000
45,197,Australia,AUS,1994,16.8601,0.017400,0.005500,16.150000,0.696500
46,198,Australia,AUS,1995,17.1189,0.021150,0.007000,15.631000,0.825500
47,199,Australia,AUS,1996,17.3911,0.025600,0.007000,15.968500,0.946500
48,200,Australia,AUS,1997,17.7901,0.030650,0.007500,15.952500,0.997000
49,201,Australia,AUS,1998,18.2222,0.035600,0.018000,15.798000,1.081000
50,202,Australia,AUS,1999,18.4477,0.040600,0.043000,16.281500,1.133500
51,203,Australia,AUS,2000,18.5252,0.046750,0.134000,16.466500,0.889500
52,204,Australia,AUS,2001,18.7789,0.054150,0.287000,16.123500,0.797500
53,205,Australia,AUS,2002,18.9220,0.058300,0.533550,16.095000,1.266800
54,206,Australia,AUS,2003,19.0191,0.063200,0.704050,16.210550,1.691800
55,207,Australia,AUS,2004,19.4554,0.072950,0.795000,15.686650,2.815250
56,208,Australia,AUS,2005,19.2086,0.084050,1.299050,15.465700,3.871000
57,209,Australia,AUS,2006,19.3554,0.097500,2.162100,14.945100,3.932500
58,210,Australia,AUS,2007,19.2159,0.113750,2.852100,13.048950,4.275000
59,211,Australia,AUS,2008,19.2034,0.139200,3.458450,11.815150,3.696100

,Entity,Code,Year,Annual CO2 emissions (per capita),Renewable electricity per capita (kWh)
0,Afghanistan,AFG,2000,0.0365,14.918
1,Afghanistan,AFG,2001,0.0369,23.141
2,Afghanistan,AFG,2002,0.0465,24.778
3,Afghanistan,AFG,2003,0.0501,26.604
4,Afghanistan,AFG,2004,0.0360,22.648
...,...,...,...,...,...
6083,Zimbabwe,ZWE,2016,0.7653,236.630
6084,Zimbabwe,ZWE,2017,0.6730,299.229
6085,Zimbabwe,ZWE,2018,0.8210,373.992
6086,Zimbabwe,ZWE,2019,0.7476,522.346
6087,Zimbabwe,ZWE,2020,0.7086,514.703

In [8]:
Climate_data_all_variables_df = pd.merge(Climate_data_complete_df, Climate_data_complete_generated_df)

In [9]:

Climate_data_all_variables_df.head(60)

,Unnamed: 0,Entity,Code,Year,Annual CO2 emissions (per capita),Renewables (% sub energy),Solar Generation - TWh,Wind Generation - TWh,Hydro Generation - TWh,Geo Biomass Other - TWh
0,35,Africa,AFR,2000,1.0936,6.759,0.011941,0.175500,75.245817,2.269063
1,36,Africa,AFR,2001,1.0645,6.982,0.014960,0.415580,80.864115,2.335353
2,37,Africa,AFR,2002,1.0489,7.219,0.017871,0.443584,85.181468,2.286400
3,38,Africa,AFR,2003,1.1094,6.703,0.021329,0.535599,82.872601,2.622400
4,39,Africa,AFR,2004,1.1603,6.612,0.025761,0.768281,87.405469,2.978850
5,40,Africa,AFR,2005,1.1547,6.622,0.030676,0.780382,89.065734,3.009669
6,41,Africa,AFR,2006,1.1613,6.745,0.038957,0.852566,92.244353,3.770405
7,42,Africa,AFR,2007,1.1763,6.658,0.051533,1.016223,95.340562,3.142048
8,43,Africa,AFR,2008,1.1968,6.375,0.073232,1.311778,97.157209,3.267396
9,44,Africa,AFR,2009,1.1762,6.413,0.096153,1.589231,99.761137,3.562722
10,45,Africa,AFR,2010,1.1725,6.681,0.212521,2.284582,107.426833,3.825407
11,46,Africa,AFR,2011,1.1809,6.836,0.601454,2.386504,110.444821,3.929657
12,47,Africa,AFR,2012,1.1456,6.620,0.994443,2.515630,110.952300,4.085025
13,48,Africa,AFR,2013,1.1227,6.827,0.788910,3.593447,117.638846,4.430894
14,49,Africa,AFR,2014,1.1837,7.042,1.937700,5.060073,123.726795,5.521056
15,50,Africa,AFR,2015,1.1191,7.053,3.592173,8.910686,120.167836,7.191202
16,51,Africa,AFR,2016,1.1189,6.843,5.120197,11.176371,116.718805,7.281251
17,52,Africa,AFR,2017,1.1131,7.239,6.902447,12.457774,125.816522,7.653766
18,53,Africa,AFR,2018,1.0865,7.554,8.295434,14.770723,133.140498,8.097891
19,54,Africa,AFR,2019,1.0772,7.874,10.906902,18.857729,137.215511,8.228082
20,55,Africa,AFR,2020,0.9896,8.849,12.407782,21.789843,142.574996,8.068135
21,145,Argentina,ARG,1998,3.8668,13.056,0.000017,0.032541,32.421788,0.463881
22,146,Argentina,ARG,1999,4.0388,10.695,0.000026,0.034781,26.530071,0.650455
23,147,Argentina,ARG,2000,3.8610,13.611,0.000036,0.034758,34.034010,0.675014
24,148,Argentina,ARG,2001,3.5949,17.005,0.000043,0.049361,41.903263,0.609326
25,149,Argentina,ARG,2002,3.3011,17.506,0.000047,0.073405,41.467051,0.850249
26,150,Argentina,ARG,2003,3.5347,15.428,0.000065,0.077954,39.080081,1.014080
27,151,Argentina,ARG,2004,4.0799,13.093,0.000070,0.072446,35.402879,0.900295
28,152,Argentina,ARG,2005,4.1507,13.650,0.000081,0.071720,39.350091,1.074073
29,153,Argentina,ARG,2006,4.4441,14.413,0.000090,0.069640,43.624000,1.567410
30,154,Argentina,ARG,2007,4.3908,11.898,0.000109,0.061593,37.741000,1.575709
31,155,Argentina,ARG,2008,4.6932,11.564,0.000144,0.041951,37.199000,1.693536
32,156,Argentina,ARG,2009,4.4204,12.918,0.000076,0.036832,40.783000,1.728756
33,157,Argentina,ARG,2010,4.5661,13.020,0.000086,0.025352,40.543000,2.013255
34,158,Argentina,ARG,2011,4.6048,12.648,0.001614,0.026591,39.641000,2.190206
35,159,Argentina,ARG,2012,4.5914,11.765,0.008173,0.369862,36.876000,2.453822
36,160,Argentina,ARG,2013,4.5060,12.378,0.015074,0.453355,40.700000,2.457350
37,161,Argentina,ARG,2014,4.4247,12.577,0.015944,0.619491,40.864000,2.302025
38,162,Argentina,ARG,2015,4.4667,12.636,0.014683,0.593335,41.770900,2.378259
39,163,Argentina,ARG,2016,4.3894,11.753,0.014273,0.547359,38.254393,1.963409
40,164,Argentina,ARG,2017,4.2744,12.834,0.016417,0.611567,41.542979,2.383655
41,165,Argentina,ARG,2018,4.0824,12.643,0.108130,1.412743,41.647865,0.473010
42,166,Argentina,ARG,2019,3.7419,13.380,0.799698,4.995966,37.066787,0.622945
43,167,Argentina,ARG,2020,3.4733,12.886,1.344341,9.470298,30.543592,0.413941
44,196,Australia,AUS,1993,16.5495,4.471,0.014600,0.002000,16.387000,0.670000
45,197,Australia,AUS,1994,16.8601,4.251,0.017400,0.005500,16.150000,0.696500
46,198,Australia,AUS,1995,17.1189,3.978,0.021150,0.007000,15.631000,0.825500
47,199,Australia,AUS,1996,17.3911,3.973,0.025600,0.007000,15.968500,0.946500
48,200,Australia,AUS,1997,17.7901,3.887,0.030650,0.007500,15.952500,0.997000
49,201,Australia,AUS,1998,18.2222,3.784,0.035600,0.018000,15.798000,1.081000
50,202,Australia,AUS,1999,18.4477,3.757,0.040600,0.043000,16.281500,1.133500
51,203,Australia,AUS,2000,18.5252,3.788,0.046750,0.134000,16.466500,0.889500
52,204,Australia,AUS,2001,18.7789,3.686,0.054150,0.287000,16.123500,0.797500
53,205,Australia,AUS,2002,18.9220,3.734,0.058300,0.533550,16.095000,1.266800
54,206,Australia,AUS,2003,19.0191,3.798,0.063200,0.704050,16.210550,1.691800
55,207,Australia,AUS,2004,19.4554,3.782,0.072950,0.795000,15.686650,2.815250
56,208,Australia,AUS,2005,19.2086,4.010,0.084050,1.299050,15.465700,3.871000
57,209,Australia,AUS,2006,19.3554,3.918,0.097500,2.162100,14.945100,3.932500
58,210,Australia,AUS,2007,19.2159,3.689,0.113750,2.852100,13.048950,4.275000
59,211,Australia,AUS,2008,19.2034,3.437,0.139200,3.458450,11.815150,3.696100

In [10]:
Climate_data_all_variables_df.drop(['Unnamed: 0'], axis=1)

,Entity,Code,Year,Annual CO2 emissions (per capita),Renewables (% sub energy),Solar Generation - TWh,Wind Generation - TWh,Hydro Generation - TWh,Geo Biomass Other - TWh
0,Africa,AFR,2000,1.0936,6.759,0.011941,0.175500,75.245817,2.269063
1,Africa,AFR,2001,1.0645,6.982,0.014960,0.415580,80.864115,2.335353
2,Africa,AFR,2002,1.0489,7.219,0.017871,0.443584,85.181468,2.286400
3,Africa,AFR,2003,1.1094,6.703,0.021329,0.535599,82.872601,2.622400
4,Africa,AFR,2004,1.1603,6.612,0.025761,0.768281,87.405469,2.978850
...,...,...,...,...,...,...,...,...,...
454,Romania,ROU,2016,3.7458,17.975,1.820000,6.590000,18.028000,0.531000
455,Romania,ROU,2017,3.9281,15.801,1.856000,7.407000,14.494000,0.525168
456,Romania,ROU,2018,3.9787,16.634,1.771000,6.322000,17.663900,0.437130
457,Romania,ROU,2019,3.8651,15.962,1.778000,6.773000,15.580921,0.504144
458,Romania,ROU,2020,3.7154,16.228,1.703000,6.955000,15.087386,0.575069

,Unnamed: 0_x,Entity,Code,Year,Annual CO2 emissions (per capita),Renewable electricity per capita (kWh),Unnamed: 0_y,Renewables (% sub energy),Solar Generation - TWh,Wind Generation - TWh,Hydro Generation - TWh,Geo Biomass Other - TWh
0,21,Africa,AFR,2000,1.0936,95.341,35,6.759,0.011941,0.175500,75.245817,2.269063
1,22,Africa,AFR,2001,1.0645,101.444,36,6.982,0.014960,0.415580,80.864115,2.335353
2,23,Africa,AFR,2002,1.0489,101.457,37,7.219,0.017871,0.443584,85.181468,2.286400
3,24,Africa,AFR,2003,1.1094,97.575,38,6.703,0.021329,0.535599,82.872601,2.622400
4,25,Africa,AFR,2004,1.1603,101.360,39,6.612,0.025761,0.768281,87.405469,2.978850
5,26,Africa,AFR,2005,1.1547,101.719,40,6.622,0.030676,0.780382,89.065734,3.009669
6,27,Africa,AFR,2006,1.1613,102.703,41,6.745,0.038957,0.852566,92.244353,3.770405
7,28,Africa,AFR,2007,1.1763,102.531,42,6.658,0.051533,1.016223,95.340562,3.142048
8,29,Africa,AFR,2008,1.1968,102.134,43,6.375,0.073232,1.311778,97.157209,3.267396
9,30,Africa,AFR,2009,1.1762,103.283,44,6.413,0.096153,1.589231,99.761137,3.562722
10,31,Africa,AFR,2010,1.1725,112.469,45,6.681,0.212521,2.284582,107.426833,3.825407
11,32,Africa,AFR,2011,1.1809,110.933,46,6.836,0.601454,2.386504,110.444821,3.929657
12,33,Africa,AFR,2012,1.1456,109.445,47,6.620,0.994443,2.515630,110.952300,4.085025
13,34,Africa,AFR,2013,1.1227,112.987,48,6.827,0.788910,3.593447,117.638846,4.430894
14,35,Africa,AFR,2014,1.1837,120.744,49,7.042,1.937700,5.060073,123.726795,5.521056
15,36,Africa,AFR,2015,1.1191,120.429,50,7.053,3.592173,8.910686,120.167836,7.191202
16,37,Africa,AFR,2016,1.1189,118.496,51,6.843,5.120197,11.176371,116.718805,7.281251
17,38,Africa,AFR,2017,1.1131,122.149,52,7.239,6.902447,12.457774,125.816522,7.653766
18,39,Africa,AFR,2018,1.0865,127.751,53,7.554,8.295434,14.770723,133.140498,8.097891
19,40,Africa,AFR,2019,1.0772,128.136,54,7.874,10.906902,18.857729,137.215511,8.228082
20,41,Africa,AFR,2020,0.9896,130.300,55,8.849,12.407782,21.789843,142.574996,8.068135
21,204,Argentina,ARG,1998,3.8668,912.786,145,13.056,0.000017,0.032541,32.421788,0.463881
22,205,Argentina,ARG,1999,4.0388,746.296,146,10.695,0.000026,0.034781,26.530071,0.650455
23,206,Argentina,ARG,2000,3.8610,792.768,147,13.611,0.000036,0.034758,34.034010,0.675014
24,207,Argentina,ARG,2001,3.5949,1001.726,148,17.005,0.000043,0.049361,41.903263,0.609326
25,208,Argentina,ARG,2002,3.3011,968.108,149,17.506,0.000047,0.073405,41.467051,0.850249
26,209,Argentina,ARG,2003,3.5347,908.688,150,15.428,0.000065,0.077954,39.080081,1.014080
27,210,Argentina,ARG,2004,4.0799,808.740,151,13.093,0.000070,0.072446,35.402879,0.900295
28,211,Argentina,ARG,2005,4.1507,895.793,152,13.650,0.000081,0.071720,39.350091,1.074073
29,212,Argentina,ARG,2006,4.4441,1001.021,153,14.413,0.000090,0.069640,43.624000,1.567410
30,213,Argentina,ARG,2007,4.3908,802.080,154,11.898,0.000109,0.061593,37.741000,1.575709
31,214,Argentina,ARG,2008,4.6932,794.907,155,11.564,0.000144,0.041951,37.199000,1.693536
32,215,Argentina,ARG,2009,4.4204,873.211,156,12.918,0.000076,0.036832,40.783000,1.728756
33,216,Argentina,ARG,2010,4.5661,858.769,157,13.020,0.000086,0.025352,40.543000,2.013255
34,217,Argentina,ARG,2011,4.6048,807.106,158,12.648,0.001614,0.026591,39.641000,2.190206
35,218,Argentina,ARG,2012,4.5914,767.090,159,11.765,0.008173,0.369862,36.876000,2.453822
36,219,Argentina,ARG,2013,4.5060,853.872,160,12.378,0.015074,0.453355,40.700000,2.457350
37,220,Argentina,ARG,2014,4.4247,828.848,161,12.577,0.015944,0.619491,40.864000,2.302025
38,221,Argentina,ARG,2015,4.4667,812.761,162,12.636,0.014683,0.593335,41.770900,2.378259
39,222,Argentina,ARG,2016,4.3894,734.800,163,11.753,0.014273,0.547359,38.254393,1.963409
40,223,Argentina,ARG,2017,4.2744,786.578,164,12.834,0.016417,0.611567,41.542979,2.383655
41,224,Argentina,ARG,2018,4.0824,765.760,165,12.643,0.108130,1.412743,41.647865,0.473010
42,225,Argentina,ARG,2019,3.7419,754.343,166,13.380,0.799698,4.995966,37.066787,0.622945
43,226,Argentina,ARG,2020,3.4733,784.365,167,12.886,1.344341,9.470298,30.543592,0.413941
44,353,Australia,AUS,1993,16.5495,969.914,196,4.471,0.014600,0.002000,16.387000,0.670000
45,354,Australia,AUS,1994,16.8601,947.798,197,4.251,0.017400,0.005500,16.150000,0.696500
46,355,Australia,AUS,1995,17.1189,916.166,198,3.978,0.021150,0.007000,15.631000,0.825500
47,356,Australia,AUS,1996,17.3911,931.736,199,3.973,0.025600,0.007000,15.968500,0.946500
48,357,Australia,AUS,1997,17.7901,923.884,200,3.887,0.030650,0.007500,15.952500,0.997000
49,358,Australia,AUS,1998,18.2222,910.990,201,3.784,0.035600,0.018000,15.798000,1.081000
50,359,Australia,AUS,1999,18.4477,931.362,202,3.757,0.040600,0.043000,16.281500,1.133500
51,360,Australia,AUS,2000,18.5252,900.932,203,3.788,0.046750,0.134000,16.466500,0.889500
52,361,Australia,AUS,2001,18.7789,906.501,204,3.686,0.054150,0.287000,16.123500,0.797500
53,362,Australia,AUS,2002,18.9220,894.267,205,3.734,0.058300,0.533550,16.095000,1.266800
54,363,Australia,AUS,2003,19.0191,942.715,206,3.798,0.063200,0.704050,16.210550,1.691800
55,364,Australia,AUS,2004,19.4554,976.375,207,3.782,0.072950,0.795000,15.686650,2.815250
56,365,Australia,AUS,2005,19.2086,978.762,208,4.010,0.084050,1.299050,15.465700,3.871000
57,366,Australia,AUS,2006,19.3554,1032.334,209,3.918,0.097500,2.162100,14.945100,3.932500
58,367,Australia,AUS,2007,19.2159,1000.653,210,3.689,0.113750,2.852100,13.048950,4.275000
59,368,Australia,AUS,2008,19.2034,866.761,211,3.437,0.139200,3.458450,11.815150,3.696100

,Entity,Code,Year,Annual CO2 emissions (per capita),Renewable electricity per capita (kWh),Renewables (% sub energy),Solar Generation - TWh,Wind Generation - TWh,Hydro Generation - TWh,Geo Biomass Other - TWh
0,Africa,AFR,2000,1.0936,95.341,6.759,0.011941,0.175500,75.245817,2.269063
1,Africa,AFR,2001,1.0645,101.444,6.982,0.014960,0.415580,80.864115,2.335353
2,Africa,AFR,2002,1.0489,101.457,7.219,0.017871,0.443584,85.181468,2.286400
3,Africa,AFR,2003,1.1094,97.575,6.703,0.021329,0.535599,82.872601,2.622400
4,Africa,AFR,2004,1.1603,101.360,6.612,0.025761,0.768281,87.405469,2.978850
...,...,...,...,...,...,...,...,...,...,...
453,Romania,ROU,2016,3.7458,1362.377,17.975,1.820000,6.590000,18.028000,0.531000
454,Romania,ROU,2017,3.9281,1235.883,15.801,1.856000,7.407000,14.494000,0.525168
455,Romania,ROU,2018,3.9787,1342.656,16.634,1.771000,6.322000,17.663900,0.437130
456,Romania,ROU,2019,3.8651,1271.911,15.962,1.778000,6.773000,15.580921,0.504144
457,Romania,ROU,2020,3.7154,1279.260,16.228,1.703000,6.955000,15.087386,0.575069

,Entity,Code,Year,Annual CO2 emissions (per capita),Renewable electricity per capita (kWh),Renewables (% sub energy),Solar Generation - TWh,Wind Generation - TWh,Hydro Generation - TWh,Geo Biomass Other - TWh
0,Africa,AFR,2000,1.0936,95.341,6.759,0.011941,0.175500,75.245817,2.269063
1,Africa,AFR,2001,1.0645,101.444,6.982,0.014960,0.415580,80.864115,2.335353
2,Africa,AFR,2002,1.0489,101.457,7.219,0.017871,0.443584,85.181468,2.286400
3,Africa,AFR,2003,1.1094,97.575,6.703,0.021329,0.535599,82.872601,2.622400
4,Africa,AFR,2004,1.1603,101.360,6.612,0.025761,0.768281,87.405469,2.978850
...,...,...,...,...,...,...,...,...,...,...
453,Romania,ROU,2016,3.7458,1362.377,17.975,1.820000,6.590000,18.028000,0.531000
454,Romania,ROU,2017,3.9281,1235.883,15.801,1.856000,7.407000,14.494000,0.525168
455,Romania,ROU,2018,3.9787,1342.656,16.634,1.771000,6.322000,17.663900,0.437130
456,Romania,ROU,2019,3.8651,1271.911,15.962,1.778000,6.773000,15.580921,0.504144
457,Romania,ROU,2020,3.7154,1279.260,16.228,1.703000,6.955000,15.087386,0.575069

In [11]:
Climate_data_all_variables_df.to_csv('Climate_data_2_variables.csv')